### ISSUE TITLE
Import Errors on Ubuntu 16.10

### ISSUE THREAD

**Issue by arbox** [mrkn/pycall#4]
Dear @mrkn ,

I'm trying to run examples from this repo, but I cannot go further the first require statement:

    irb(main):001:0> require 'pycall/import'
    LoadError: no library specified
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:176:in `ffi_libraries'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:336:in `attach_variable'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170311/lib/pycall/libpython.rb:106:in `<module:LibPython>'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170311/lib/pycall/libpython.rb:4:in `<module:PyCall>'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170311/lib/pycall/libpython.rb:3:in `<top (required)>'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170311/lib/pycall.rb:2:in `<top (required)>'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/pycall-0.1.0.alpha.20170311/lib/pycall/import.rb:1:in `<top (required)>'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/arbox/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /home/arbox/.rbenv/versions/2.4.0/bin/irb:11:in `<main>'

Setting PYTHONHOME and PYTHONPATH does not change the picture.

Could you please provide requirements for the Python side as well? Thank you!

**Comment by mrkn** [comment]
@arbox How do you install python?

Pycall uses `PYTHON` environment variable to find Python's executable such as `/usr/bin/python3`.
This environment variable is referred to execute [investigator.py](https://github.com/mrkn/pycall/blob/master/lib/pycall/python/investigator.py) script, which investigates the installation directory and the path of shared library of the specified Python environment.

If you installed python into a non-standard location, please do either:

- Specify the full-path of python command in `PYTHON` environment variable
- Specify the name of python command in `PYTHON` and put the `bin` directory in `PATH`.

**Comment by arbox** [comment]
Hi, @mrkn, thank you for a reply!

Python is installed on my machine pretty standard, from the Ubuntu repositories.

I looked up your Travis configuration, so at least `python python-dev python-all` as well `python3 python3-dev python3-all` are installed. It's a fresh Ubuntu 16.10 installation.

I could run `investigator.py` manually with the following output:

    executable: /usr/bin/python
    exec_prefix: /usr
    prefix: /usr
    VERSION: 2.7
    LIBRARY: libpython2.7.a
    LDLIBRARY: libpython2.7.so
    LIBDIR: /usr/lib
    PYTHONFRAMEWORKPREFIX:

Could I do something to provide you with additional debug info? Thank you!

**Comment by mrkn** [comment]
I could reproduce this issue with ubuntu 16.10 on VMware.
And I found the reason of this issue.  It is due to multiarch support of Ubuntu (and Debian).

While Python said that the libdir is `/usr/lib`, but ubuntu's python package put libpython in `/usr/lib/x86_64-linux-gnu`.

Probably Python does not know libpython is located in `/usr/lib/x86_64-linux-gnu`.
If so, I cannot resolve the path of libpython from the information obtained by investigator.py.

**Comment by mrkn** [comment]
@arbox Now you can specify libpython's full path in LIBPYTHON environment variable.
On Ubuntu 16.10, `LIBPYTHON=/usr/lib/x86_64-linux-gnu/libpython2.7.so.1` for Python 2.7 or `LIBPYTHON=/usr/lib/x86_64-linux-gnu/libpython3.5m.so.1` for Python 3.5 can be used.
Try again.

**Comment by arbox** [comment]
@mrkn thank you! Cool support here! And very demanded library for Ruby :)

**Comment by mrkn** [comment]
@arbox I've released the new version of pycall.  The latest pycall supports multiarch system in Debian and Ubuntu.  Check it.
