### ISSUE TITLE
Support multiarch in Debian and Ubuntu by a sophisticated way

### ISSUE THREAD

**Issue by mrkn** [mrkn/pycall#8]
Now we can use `LIBPYTHON` environment variable to specify libpython's location directly.
But I want pycall to resolve libpython's location for Debian and Ubuntu.
I need to know how to detect the location of multiarch libdir, such as `/usr/lib/x86_64-linux-gnu` for amd64 architecture.

**Comment by bongole** [comment]
Debian and Ubuntu version python has "MULTIARCH" config variable.
https://wiki.debian.org/Python/MultiArch

**Comment by mrkn** [comment]
@bongole Thank you so much.  I think I can fix this issue by using `MULTIARCH` config variable :+1:
